In [1]:
#data collection
import pandas as pd
dataset=pd.read_csv("CKD.csv")

In [2]:
#data preprocessing
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [3]:
#input split
independent=dataset.drop('classification_yes', axis=1)
#ouput split
dependent=dataset[['classification_yes']]

In [4]:
#train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [5]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [6]:
#model creation
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
param_grid={'criterion':['gini','entropy'], 'max_features':['auto','sqrt','log2'],'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeClassifier(),param_grid, refit=True, verbose=3, n_jobs=1, scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5] END criterion=gini, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 2/5] END criterion=gini, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 3/5] END criterion=gini, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 4/5] END criterion=gini, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 5/5] END criterion=gini, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 1/5] END criterion=gini, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 2/5] END criterion=gini, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 3/5] END criterion=gini, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 4/5] END criterion=gini, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 5/5] END criterion=gini, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 1/5] END criterion=gini, max_features=sqrt, splitter=best;, score=0.947 total time=   0.0s
[CV 2/5] END criterion=gini, max_features=sqrt, splitter=best;, score=0.909 total time=   0.0s
[CV 3/5] END criterion=gini, max_features=sqrt, splitter=best;, score=0.982 total time=   0.0s
[CV 4/5] END criterion=gini, max_features=sqrt, splitter=best;, score=0.838 total time=   0.0s
[CV 5/5] END criterion=gini, max_features=sqrt, splitter=best;, score=0.945 total time=   0.0s
[CV 1/5] END criterion=gini, max_features=sqrt, splitter=random;, score=0.982 total time=   0.0s
[CV 2/5] END criterion=gini, max_features=sqrt, splitter=random;, score=0.964 total time=   0.0s
[CV 3/5] END criterion=gini, max_features=sqrt, splitter=random;, score=0.912 total time=   0.0s
[CV 4/5] END criterion=gini, max_features=sqrt, splitter=random;, score=0.964 total time=   0.0s
[CV 5/5] END criterion=gini, max_features=sqrt, splitter=random;, score=0.982 total time=   0.0s
[CV 1/5] END criterion=gini, max_features=log2, splitter=best;, score=0.982 total time=   0.0s
[CV 2/5] END criterion=gini, max_features=log2, splitter=best;, score=0.945 total time=   0.0s
[CV 3/5] END criterion=gini, max_features=log2, splitter=best;, score=0.965 total time=   0.0s
[CV 4/5] END criterion=gini, max_features=log2, splitter=best;, score=0.982 total time=   0.0s
[CV 5/5] END criterion=gini, max_features=log2, splitter=best;, score=0.945 total time=   0.0s
[CV 1/5] END criterion=gini, max_features=log2, splitter=random;, score=0.965 total time=   0.0s
[CV 2/5] END criterion=gini, max_features=log2, splitter=random;, score=0.964 total time=   0.0s
[CV 3/5] END criterion=gini, max_features=log2, splitter=random;, score=0.877 total time=   0.0s
[CV 4/5] END criterion=gini, max_features=log2, splitter=random;, score=0.947 total time=   0.0s
[CV 5/5] END criterion=gini, max_features=log2, splitter=random;, score=0.946 total time=   0.0s
[CV 1/5] END criterion=entropy, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 2/5] END criterion=entropy, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 3/5] END criterion=entropy, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 4/5] END criterion=entropy, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 5/5] END criterion=entropy, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 1/5] END criterion=entropy, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 2/5] END criterion=entropy, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 3/5] END criterion=entropy, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 4/5] END criterion=entropy, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 5/5] END criterion=entropy, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 1/5] END criterion=entropy, max_features=sqrt, splitter=best;, score=0.947 total time=   0.0s
[CV 2/5] END criterion=entropy, max_features=sqrt, splitter=best;, score=0.964 total time=   0.0s
[CV 3/5] END criterion=entropy, max_features=sqrt, splitter=best;, score=0.982 total time=   0.0s
[CV 4/5] END criterion=entropy, max_features=sqrt, splitter=best;, score=0.964 total time=   0.0s
[CV 5/5] END criterion=entropy, max_features=sqrt, splitter=best;, score=0.982 total time=   0.0s
[CV 1/5] END criterion=entropy, max_features=sqrt, splitter=random;, score=0.911 total time=   0.0s
[CV 2/5] END criterion=entropy, max_features=sqrt, splitter=random;, score=0.982 total time=   0.0s
[CV 3/5] END criterion=entropy, max_features=sqrt, splitter=random;, score=0.982 total time=   0.0s
[CV 4/5] END criterion=entropy, max_features=sqrt, splitter=random;, score=0.964 total time=   0.0s
[CV 5/5] END criterion=entropy, max_features=sqrt, splitter=random;, score=0.946 total time=   0.0s
[CV 1/5] END criterion=entropy, max_features=log2, splitter=best;, score=0.982 total time=   0.0s
[CV 2/5] END criterion=entropy, max_features=log2, splitter=best;, score=0.928 total time=   0.0s
[CV 3/5] END criterion=entropy, max_features=log2, splitter=best;, score=0.859 total time=   0.0s
[CV 4/5] END criterion=entropy, max_features=log2, splitter=best;, score=0.945 total time=   0.0s
[CV 5/5] END criterion=entropy, max_features=log2, splitter=best;, score=0.964 total time=   0.0s
[CV 1/5] END criterion=entropy, max_features=log2, splitter=random;, score=0.982 total time=   0.0s
[CV 2/5] END criterion=entropy, max_features=log2, splitter=random;, score=0.965 total time=   0.0s
[CV 3/5] END criterion=entropy, max_features=log2, splitter=random;, score=0.982 total time=   0.0s
[CV 4/5] END criterion=entropy, max_features=log2, splitter=random;, score=0.982 total time=   0.0s
[CV 5/5] END criterion=entropy, max_features=log2, splitter=random;, score=0.982 total time=   0.0s

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.92439861 0.96084155 0.96393358 0.93967529
        nan        nan 0.96783681 0.95702201 0.9357469  0.97859183]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [8]:
#Evaluation metrics
res=grid.cv_results_
grid_pred=grid.predict(x_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_pred)

In [9]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.92      1.00      0.96        45
           1       1.00      0.95      0.97        75

    accuracy                           0.97       120
   macro avg       0.96      0.97      0.97       120
weighted avg       0.97      0.97      0.97       120

In [10]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_pred,average='weighted')
print("The f1_macro value for best parameter{}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter{'criterion': 'entropy', 'max_features': 'log2', 'splitter': 'random'}: 0.9669192655202565

In [11]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

np.float64(0.9733333333333334)

In [12]:
table=pd.DataFrame.from_dict(res)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000296,0.000067,0.000000,0.000000,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.000231,0.000051,0.000000,0.000000,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.000893,0.000135,0.002328,0.000200,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.947015,0.909115,0.982221,0.838458,0.945185,0.924399,0.048798,8
3,0.000861,0.000187,0.002781,0.000559,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.982051,0.964286,0.911692,0.964286,0.981894,0.960842,0.025817,4
4,0.000900,0.000024,0.002629,0.000078,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.982221,0.945469,0.964572,0.982221,0.945185,0.963934,0.016503,3
5,0.000785,0.000089,0.002418,0.000303,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.964572,0.964286,0.876841,0.946663,0.946014,0.939675,0.032443,6
6,0.000259,0.000117,0.000000,0.000000,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.000248,0.000119,0.000000,0.000000,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.000934,0.000136,0.002234,0.000131,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.946663,0.964286,0.982221,0.964286,0.981728,0.967837,0.013217,2
9,0.000818,0.000102,0.002252,0.000148,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.911105,0.982051,0.982051,0.963889,0.946014,0.957022,0.026569,5
10,0.000829,0.000098,0.002970,0.001104,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.982221,0.927778,0.859355,0.945469,0.963912,0.935747,0.042301,7
11,0.000846,0.000017,0.002585,0.000008,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.982221,0.964572,0.982051,0.982221,0.981894,0.978592,0.007011,1