In [ ]:
 #1.
Q1. Create a DataFrame with the following student marks and display students with marks above 80.
{'Name': ['Anu', 'Raj', 'Diya', 'Kiran'], 'Marks': [76, 88, 95, 65]}

expected Output:
    
    Name  Marks
1   Raj     88
2  Diya     95

In [23]:
import pandas as pd
data={'Name': ['Anu', 'Raj', 'Diya', 'Kiran'], 'Marks': [76, 88, 95, 65]}
df=pd.DataFrame(data)
print(df[df['Marks']>80])

   Name  Marks
1   Raj     88
2  Diya     95

In [ ]:
#2.Q2. Create a DataFrame and find the mean salary grouped by department.
{'Name': ['Amit', 'Sneha', 'Kunal', 'Riya'], 'Department': ['HR', 'IT', 'HR', 'IT'], 'Salary': [30000, 50000, 35000, 52000]}
Expected Output:
Department
HR    32500.0
IT    51000.0
Name: Salary, dtype: float64

In [24]:
import pandas as pd
data={'Name': ['Amit', 'Sneha', 'Kunal', 'Riya'], 'Department': ['HR', 'IT', 'HR', 'IT'], 'Salary': [30000, 50000, 35000, 52000]}
df=pd.DataFrame(data)
m=df.groupby('Department')['Salary'].mean()
print(m)

Department
HR    32500.0
IT    51000.0
Name: Salary, dtype: float64

In [ ]:
 #3.Q3. Create a DataFrame and apply label encoding to the Gender column.
{'Name': ['Arjun', 'Leela', 'Kiran'], 'Gender': ['Male', 'Female', 'Male']}
Expected Output:
    Name  Gender  Gender_encoded
0  Arjun    Male               1
1  Leela  Female               0
2  Kiran    Male               1

In [27]:
import pandas as pd
data={'Name': ['Arjun', 'Leela', 'Kiran'], 'Gender': ['Male', 'Female', 'Male']}
df=pd.DataFrame(data)
from sklearn.preprocessing import LabelEncoder
df['Gender_encoded'] = LabelEncoder().fit_transform(df['Gender'])
df

    Name  Gender  Gender_encoded
0  Arjun    Male               1
1  Leela  Female               0
2  Kiran    Male               1

In [ ]:
 #4.🔹Q4. Normalize the 'Score' column using Min-Max scaling.
{'Student': ['A', 'B', 'C'], 'Score': [55, 80, 65]}

Expected Output:
    Student  Score  Normalized_Score
0       A     55               0.0
1       B     80               1.0
2       C     65               0.4

In [34]:
import pandas as pd
data={'Student': ['A', 'B', 'C'], 'Score': [55, 80, 65]}
df=pd.DataFrame(data)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(df[['Score']])
df['Normalized_score']=scaler.transform(df[['Score']])
df

  Student  Score  Normalized_score
0       A     55               0.0
1       B     80               1.0
2       C     65               0.4

In [ ]:
 #5.
Use SVM, RandomForest, and GaussianNB to classify customers as 'Buy' or 'Not Buy' based on Age and Salary.
{'Age': [22, 25, 47, 52, 46, 56, 23], 'Salary': [15000, 29000, 48000, 60000, 52000, 61000, 17000], 'Buy': [0, 0, 1, 1, 1, 1, 0]}

In [55]:
import pandas as pd
data={'Age': [22, 25, 47, 52, 46, 56, 23], 'Salary': [15000, 29000, 48000, 60000, 52000, 61000, 17000], 'Buy': [0, 0, 1, 1, 1, 1, 0]}
df=pd.DataFrame(data)
x=df.drop('Buy', axis=1)
y=df['Buy']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)
from sklearn.ensemble import RandomForestClassifier
c1=RandomForestClassifier()
c1.fit(x_train,y_train)

RandomForestClassifier()

In [56]:
from sklearn.svm import SVC
c2=SVC()
c2.fit(x_train,y_train)

SVC()

In [58]:
from sklearn.naive_bayes import GaussianNB
c3=GaussianNB()
c3.fit(x_train,y_train)

GaussianNB()

In [59]:
rf=c1.predict([[25,29000]])
print("Random Forest Prediction: ",rf)

Random Forest Prediction:  [0]

C:\Users\Jayashree M\.conda\envs\hopeai\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [60]:
sm=c2.predict([[25,29000]])
print("Random Forest Prediction: ",sm)

Random Forest Prediction:  [0]

C:\Users\Jayashree M\.conda\envs\hopeai\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [61]:
g=c3.predict([[25,29000]])
print("Random Forest Prediction: ",g)

Random Forest Prediction:  [0]

C:\Users\Jayashree M\.conda\envs\hopeai\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(